<table>
    <thead>
        <tr>
            <th>productCode</th>
            <th>productName</th>
            <th>quantity</th>
            <th>description</th>
            <th>status</th>
            <th>discount</th>
            <th>discount-type</th>
            <th>productPrice</th>
            <th>productImage</th>
            <th>created_at</th>
            <th>updated_at</th>
            <th>category_id</th>
            <th>frontImage</th>
            <th>sideImage</th>
            <th>total</th>
            <th>opening_value</th>
            <th>reOrder_quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($products as $item)
            <tr>
                <td>{{$item->productCode}}</td>
                <td>{{$item->productName}}</td>
                <td>{{$item->quantity}}</td>
                <td>{{$item->description}}</td>
                <td>{{$item->status}}</td>
                <td>{{$item->discount}}</td>
                <td>{{$item->discount}}</td>
                <td>{{$item->productPrice}}</td>
                <td>{{$item->productImage}}</td>
                <td>{{$item->created_at}}</td>
                <td>{{$item->updated_at}}</td>
                <td>{{$item->category_id}}</td>
                <td>{{$item->frontImage}}</td>
                <td>{{$item->sideImage}}</td>
                <td>{{$item->total}}</td>
                <td>{{$item->opening_value}}</td>
                <td>{{$item->reOrder_quantity}}</td>
            </tr>
        @endforeach
    </tbody>
</table>
